name: Deploy to Firebase

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Firebase tools
        run: npm i -g firebase-tools
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
